### ISSUE TITLE
In Typescript browser.imageComparison is undefined

### ISSUE THREAD

**Issue by petersenrr** [wswebcreation/webdriver-image-comparison#113]
I have a repo that is in typescript and I am trying to use this image comparison but I get the error 
```TypeError: Cannot read property 'checkScreen' of undefined```

here is the code that I thought would work that is causing the error

    expect(await browser.imageComparison.checkScreen('fullpage', {ignoreColors: true, ignoreAntialiasing: true})).to.be.below(.05);
    let visualPercentage = await browser.imageComparison.checkScreen('fullpage', {ignoreColors: true, ignoreAntialiasing: true})

**Environment:**
 - Node.js version: v14.20.0
 - NPM version: 6.14.17
 - Browser name and version: Chrome 104
 - Platform name and version: Windows 11
 - Framework name and version: Webdriverio
 - Plugin name and version: webdriver-image-comparison
 - webdriver-image-comparison version: 0.22.0

![Screen Shot 2022-08-05 at 9 45 47 AM](https://user-images.githubusercontent.com/19438180/183124056-baba6b7d-16ad-45ee-9ca3-e2fcd811960e.png)

**Comment by wswebcreation** [comment]
Normally this happens because one of the following reasons 

1. you didn’t add the typescript definition, see https://github.com/wswebcreation/wdio-image-comparison-service#typescript-support
2. You didn’t include the service (correctly).


Can you check them both and if that’s not the case then can you please provide you complete config files?

**Comment by petersenrr** [comment]
Here are my config files

tsconfig.json

{
    "compilerOptions": {
      "target": "esnext",
      "module" : "CommonJS",
      "esModuleInterop": true,
      "moduleResolution": "node",
      "types": [
        "node",
        "webdriverio/sync",
        "@wdio/mocha-framework",
         "expect-webdriverio",
         "wdio-image-comparison-service"
      ]
    },
    "include": [
      "./test/**/*.ts", "wdio.conf.ts",
    ]
  }


and config.json

{
  "default": {
    "baseHost": 
    "beforeLaunchLogin": false,
    "dataCreationBaseHost": 
    "devKey":
    "globalTimeout": 20000,
    "ignoreSynchronization": true,
    "localCode": false,
    "repository": {
      "type": "git",
      "url": 
    },
    "license":
    "loginGlobalUser": false,
    "overrideByCss": true,
    "runInParallel": true,
    "exclude": [],
    "suites": {
      "all": [
        "./test/models/model-based-tests/**/*.ts"
      ]
    },
    "plugins": [
      {
        "package": "wdio-image-comparison-service",
        "options": {
          "autoSaveBaseline": true,
          "baselineFodler": "./avtBaseline/",
          "debug": true,
          "formatImageName": "'{tag}={width}x{height}'",
          "screenshotPath": "./avtCompare/",
          "savePerInstance": true
        }
      }
    ],
    "environment": [
      {
        "platform": "Windows 11",
        "browserName": "chrome"
      }
    ],
    "logCustomEvents": true,
    "logToSplunk": true,
    "framework": "mocha",
    "maximizeWindow": false,
    "mochaOpts": {
      "timeout": 90000,
      "useColors": true,
      "bail": false,
      "retries": 2
    },
    "sauceUser": 
    "sauceKey":
    "services": ["sauce"],
    "location": "SAUCE",
    "team": "Integration"
  },
  "local": {
    "environment": [
      {
        "browserName": "chrome"
      }
    ],
    "maxThreads": 1,
    "services": ["chromedriver"],
    "sauceUser": null,
    "sauceKey": null,
    "location": null,
    "seleniumAddress": "http://localhost:4444/wd/hub"
  }
}

**Comment by wswebcreation** [comment]
You added the wdio-image-comparison-service in the plugins, it needs to be in the services

**Comment by petersenrr** [comment]
it is still not working, i am not sure what i am doing wrong

I am getting this error

```
[0-0] FAILED in chrome - /test/models/model-based-tests/zioncmsdrawio/Grid/zioncmsdrawioCard.spec.ts
[0-2] TypeError in "Promo.Navigate to ZionCMS"
TypeError: browser.checkScreen is not a function
    at Context.<anonymous> (/Users/Petersenrr/dev/qa-brightspot/test/models/model-based-tests/zioncmsdrawio/Grid/zioncmsdrawioPromo.spec.ts:8:35)

```

Here is my config.json

```
{
  "default": {
    "baseHost": 
    "beforeLaunchLogin": false,
    "dataCreationBaseHost": 
    "devKey": 
    "globalTimeout": 20000,
    "ignoreSynchronization": true,
    "localCode": false,
    "repository": {
      "type": "git",
    },
    "license": "BSD-2-Clause",
    "loginGlobalUser": false,
    "overrideByCss": true,
    "runInParallel": true,
    "exclude": [],
    "suites": {
      "all": [
        "./test/models/model-based-tests/**/*.ts"
      ]
    },
    "environment": [
      {
        "platform": "Windows 11",
        "browserName": "chrome"
      }
    ],
    "logCustomEvents": true,
    "logToSplunk": true,
    "framework": "mocha",
    "maximizeWindow": false,
    "mochaOpts": {
      "timeout": 90000,
      "useColors": true,
      "bail": false,
      "retries": 2
    },
    "sauceUser": 
    "sauceKey": 
    "services": [
      [
        "image-comparison",
          {
            "autoSaveBaseline": true,
            "baselineFolder": "./avtBaseline/",
            "debug": true,
            "formatImageName": "'{tag}={width}x{height}'",
            "screenshotPath": "./avtCompare/",
            "savePerInstance": true
          }
      ]
    ],
    "location": "SAUCE",
    "team": "Integration"
  },
  "local": {
    "environment": [
      {
        "browserName": "chrome"
      }
    ],
    "maxThreads": 1,
    "services": ["chromedriver"],
    "sauceUser": null,
    "sauceKey": null,
    "location": null,
    "seleniumAddress": "http://localhost:4444/wd/hub"
  }
}
```

Here is my Test

```
import Grid from '../../../../models/model-based-pages/Grid.page'
import { expect } from 'chai';

describe('Card', function() {
  it('Navigate to ZionCMS', async () => {
    await browser.url('https://beta.familysearch.org/zion-cms-qa/test1');
    expect(await browser.checkScreen('fullpage', {ignoreColors: true, ignoreAntialiasing: true})).to.be.below(.05);
    let visualPercentage = await browser.checkScreen('fullpage', {ignoreColors: true, ignoreAntialiasing: true})
    console.log('The MisMatch Percentage of your Comparison is ' + visualPercentage + '\n')
    await browser.waitUntil(async function () {return (await Grid.CardTextBox.isDisplayed())}, {timeout: 25000})
    expect(await (await Grid.CardTextBox).isDisplayed()).to.be.true;
    await browser.waitUntil(async function () {return (await Grid.CardText.isDisplayed())}, {timeout: 25000})
    await (await Grid.CardText).waitUntil(async function () {return (await this.getText()).includes("Card link to Google")}, {timeout: 10000})
    expect(await (await Grid.CardText).getText()).to.include("Card link to Google");
  })
})
```
