### ISSUE TITLE
Make image comparison function support Node 18

### ISSUE THREAD

**Issue by mhdSid** [wswebcreation/webdriver-image-comparison#116]
**Is your feature request related to a problem? Please describe.**
"resemblejs" has a dependency on "canvas" library which doesn't support NodeJs v.18, therefore, I would like to request that "webdriver-image-comparison" to support NodeJs v.18

**Describe the solution you'd like**
Use [pixelmatch](https://github.com/mapbox/pixelmatch)

**Describe alternatives you've considered**
Create pre-builds for Node 18 within "canvas" library; there is one open [issue](https://github.com/Automattic/node-canvas/issues/2025) for this. 

**Additional context**
-

**Comment by wswebcreation** [comment]
Hi @mhdSid 

Tnx for this issue. I'll release a new version soon with support for Nodejs 18.

For now I want to stick to canvas because it's a bit more flexible but I do like the alternatives. Something to investigate, thanks!
