### ISSUE TITLE
 Indicate when baseline image was missing/created

### ISSUE THREAD

**Issue by smichaelsen** [wswebcreation/webdriver-image-comparison#127]
When the CI runs our visual tests then I assume that we have baseline images for all of our cases. However images can be forgotten to be pushed, accidentally deleted, screen resolution changes and with it the file name, etc.

In all these cases our tests will pass, because the check function silently creates the baseline image and returns a result with misMatchPercentage: 0. It would be great if the result could contain an additional property like baselineImageCreated: 1 to indicate what happened. Our test code could react to it and fail the test in a CI scenario.

**Comment by wswebcreation** [comment]
Hi @smichaelsen 

Thanks for your ticket, I'm assuming you added `autoSaveBaseline: true` in your config when you start your CI. This is not something what I would suggest, but feel free to submit a PR, then please change the result to `baselineImageCreated: boolean`

**Comment by smichaelsen** [comment]
You are right, I missed the `autoSaveBaseline` option. Disabling it in the CI helped me. I'm note interested anymore in my suggested feature, and if you're not either then it can be closed.
Thanks for the helpful response!

**Comment by wswebcreation** [comment]
Closing this then. Thanks
