### ISSUE TITLE
Remove console output "ignoredBoxes"

### ISSUE THREAD

**Issue by camueller** [wswebcreation/webdriver-image-comparison#13]
**Environment (please complete the following information):**
 - webdriver-image-comparison version: [e.g. 1.0.0]
0.4.5

Console log is flooded with "ignoredBoxes" created by lib/methods/images.ts line 135.
Please remove this console output:
console.log('ignoredBoxes = ', ignoredBoxes);

**Comment by wswebcreation** [comment]
Tnx!

Removed it and released a new version `0.4.6`
