### ISSUE TITLE
Error: Unsupported image type

### ISSUE THREAD

**Issue by JohnRobPeter** [wswebcreation/webdriver-image-comparison#15]
Hi, is the element screen shot supported? I have this error each time I run the element comparison. 
*Note: it works fine for checkScreen 

 - Node.js version: v8.9.4
 - NPM version: 6.9.0
 - Browser name and version: Chrome 74.0.3729.131 (Official Build) (64-bit)
 - Platform name and version: Windows 10
 - Framework name and version: Protractor 5.3.1 (protractor-cucumber-framework) 
 - Plugin name and version: protractor-image-comparison 3.1.1

**Config of the automation framework + plugin**
```
plugins: [
        {
            // The module name
            package: 'protractor-image-comparison',
            // Some options, see the docs for more
            options: {
                baselineFolder: path.resolve(process.cwd(), './baseline/'),
                formatImageName: `{tag}-{browserName}-{width}x{height}`,
                screenshotPath: path.resolve(process.cwd(), './screenshots/'),
                savePerInstance: true,
                autoSaveBaseline: true,
                debug: true,
                // ... more options
            },
        },
    ],
```
**Describe the bug**
AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Unsupported image type'
and the saved images is only 3bytes in size that is only header in there

**To Reproduce**
```
expect(await browser.imageComparison.checkElement(element(by.xpath('.//logo')), sourceName, { /* some options*/ })).toEqual(0)
```

**Expected behavior**
An image should be saved the same way it is for checkScreen

**Log**
Though the debug is enabled no real logs are shown in the console for this plugin

**Comment by wswebcreation** [comment]
Hi @JohnRobPeter 

Thanks for filing an issue, can you please provide your complete config with the capabilities. Then I can debug it for you
