### ISSUE TITLE
'saveScreen' method does not work on pages with '*/xml' content type 

### ISSUE THREAD

**Issue by idem7x** [wswebcreation/webdriver-image-comparison#30]
**Environment (please complete the following information):**
 - Node.js version: [10.16.0]
 - NPM version: [6.9.0]
 - Browser name and version: [Firefox, IE, Edge]
 - Platform name and version: [Windows 10, Mac OS X]
 - Framework name and version: [@wdio/jasmine-framework 5.11.0 ]
 - Plugin name and version: [wdio-image-comparison-service 1.3.0]
 - webdriver-image-comparison version: [0.6.0]

**Config of the automation framework + plugin**
```javascript
services: [
    ['image-comparison',
      {
        baselineFolder: join(process.cwd(), './tools/jasmine/image/expected/'),
        formatImageName: '{tag}-{width}x{height}',
        screenshotPath: join(process.cwd(), './tools/jasmine/image/actual'),
        savePerInstance: true,
        autoSaveBaseline: true,
        blockOutStatusBar: true,
        blockOutToolBar: true,
        returnAllCompareData: true,
        clearRuntimeFolder: true
      }
    ]
  ]
```
**Describe the bug**
In case of visit any page with content type 'text/xml', 'application/xml', 'application/xhtml', 'saveScreen' method can't make screenshot on page due to different reasons:
- Firefox 68 - `javascript error: TypeError: document.body is null`
- IE 11- `Error: JavaScript error`
- Edge 17 - `Error: Unable to get property 'style' of undefined or null reference`

However, it correctly works on Chrome 75 and Safari 12.

**To Reproduce**
```javascript
describe('XML tests', () => {
    it('XML is correctly displayed for content type text xml', () => {
      browser.url('put here any site with text/xml content type');
      browser.pause(3000);
      browser.saveScreen('test');
  });
});
```
**Expected behavior**
Screenshot should be taken.

**Log**
Example for Firefox: 
```
2019-07-29T16:29:32.757Z INFO webdriver: COMMAND navigateTo("testPage.xml")
2019-07-29T16:29:32.758Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/aeae0af7-b890-df49-83b1-5c8b07a1e3ca/url
2019-07-29T16:29:32.758Z INFO webdriver: DATA { url:
   'testPage.xml' }
2019-07-29T16:29:35.942Z INFO webdriver: COMMAND saveScreen("test")
2019-07-29T16:29:35.944Z INFO webdriver: COMMAND executeScript("return (function hideScrollBars(hide) {
    if (hide) {
        document.body.style.overflow = 'hidden';
    }
    else {
        document.body.style.overflow = '';
    }
}).apply(null, arguments)", <object>)
2019-07-29T16:29:35.945Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/aeae0af7-b890-df49-83b1-5c8b07a1e3ca/execute/sync
2019-07-29T16:29:35.945Z INFO webdriver: DATA { script:
   'return (function hideScrollBars(hide) {\n    if (hide) {\n        document.body.style.overflow = \'hidden\';\n    }\n    else {\n        document.body.style.overflow = \'\';\n    }\n}).apply(null, arguments)',
  args: [ true ] }
2019-07-29T16:29:35.951Z DEBUG webdriver: request failed due to response error: javascript error
2019-07-29T16:29:35.951Z WARN webdriver: Request failed due to TypeError: document.body is null
```

**Comment by wswebcreation** [comment]
Hi @idem7x 

Thanks for filling an issue, can you provide some more info, or an example project so I can verify what's wrong? 
Secondly, are you executing this on a local machine or on a cloudservice? If so, can you provide you complete config and as said maybe an example repo. That would really help me debug this

**Comment by idem7x** [comment]
Hi @wswebcreation 

I added project here - https://github.com/idem7x/wdioxmltest.
It reproduces both on local machine and Saucelabs.

**Comment by wswebcreation** [comment]
Thanks for this, I'll dive into it hopefully before my vacation.

**Comment by wswebcreation** [comment]
@idem7x 

I've release a new version, https://github.com/wswebcreation/wdio-image-comparison-service/releases/tag/v1.5.1, can you please check if it works for you and close if fixed?

**Comment by maxzaselian-okta** [comment]
@wswebcreation ,
Thanks for fix! 
For Firefox and Edge it works like a charm, but for IE I got another issue... 
But this could be related to Jasmine. 
`1) XML tests XML is correctly displayed for content type 
[internet explorer 11 WINDOWS #0-0] RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
[internet explorer 11 WINDOWS #0-0]     at <Jasmine>
[internet explorer 11 WINDOWS #0-0]     at boundsError (internal/buffer.js:47:11)
[internet explorer 11 WINDOWS #0-0]     at Buffer.readUInt32BE (internal/buffer.js:192:5)
[internet explorer 11 WINDOWS #0-0]     at UserContext.it (/Users/idem7x/wdioxmltest/test/specs/xml.js:5:13)`

**Comment by idem7x** [comment]
@wswebcreation ,
Thanks for fix! 
For Firefox and Edge it works like a charm, but for IE I got another issue... 
But this could be related to Jasmine. 

> 1) XML tests XML is correctly displayed for content type 
> [internet explorer 11 WINDOWS #0-0] RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
> [internet explorer 11 WINDOWS #0-0]     at <Jasmine>
> [internet explorer 11 WINDOWS #0-0]     at boundsError (internal/buffer.js:47:11)
> [internet explorer 11 WINDOWS #0-0]     at Buffer.readUInt32BE (internal/buffer.js:192:5)
> [internet explorer 11 WINDOWS #0-0]     at UserContext.it (/Users/idem7x/wdioxmltest/test/specs/xml.js:5:13)

**Comment by wswebcreation** [comment]
@idem7x 

Hmm, strange, I checked this on my Sauce Labs open source account and it works, here's the instance

https://app.eu-central-1.saucelabs.com/tests/7737d466f1384182af2f93a8498ec585#8

The test is flagged as failed due to the fact that I didn't had a baseline image, but here it works.

I'm going to close it now, it's still open for discussion
