### ISSUE TITLE
not able to make the page scroll with saveFullPageScreen()

### ISSUE THREAD

**Issue by davelee-scmp** [wswebcreation/webdriver-image-comparison#31]
**Environment:**
 - Node.js version: 11.9.0
 - NPM version: 6.5.0
 - Browser name and version: Chrome 75
 - Platform name and version: Windows 10
 - webdriver-image-comparison version: 1.5.0

**Describe the bug**
not able to make the page scroll with saveFullPageScreen() on the following page:
https://www.cpjobs.com/hk/article/hong-kong-international-school-teacher-recruitment-fair

**Comment by wswebcreation** [comment]
Thanks for filling an issue, I will dive into this but I'm currently on a holiday, so I don't have time to fix it fast.

It's related to this piece of code I need to refactor https://github.com/wswebcreation/webdriver-image-comparison/blob/master/lib/clientSideScripts/scrollToPosition.ts

**Comment by wswebcreation** [comment]
@davelee-scmp 

I've release a new version, https://github.com/wswebcreation/wdio-image-comparison-service/releases/tag/v1.5.1, can you please check if it works for you?

**Comment by wswebcreation** [comment]
Going to close it now, it works as expected

![fullPage-chrome-1200x1373-dpr-1](https://user-images.githubusercontent.com/11979740/63639501-1f0e4880-c694-11e9-8566-c3a0aafda75b.png)

**Comment by davelee-scmp** [comment]
@wswebcreation Yes it is working, thanks a lot!
