### ISSUE TITLE
tslint doesn't work

### ISSUE THREAD

**Issue by ds1971** [wswebcreation/webdriver-image-comparison#37]
In order to use tslint, I had to manually copy packages `vrsource-tslint-rules` and `tslint-eslint-rules` to `/node_modules/webdriver-image-comparison/node_modules`.
Otherwise, I got an error:

```
$ tslint --fix '**/*.ts' && tsc --project tsconfig.json --noEmit
Failed to load .../offer-checkout-2.0/node_modules/webdriver-image-comparison/tslint.json: Could not find custom rule directory: node_modules/vrsource-tslint-rules/rules
```
Also, I had to manually install vrsource-tslint-rules and  tslint-eslint-rules.

**Comment by wswebcreation** [comment]
Hi @ds1971 

Sorry for my late response. I need to look into this and fix it, or maybe if you have time for it you might be able to create a PR
