### ISSUE TITLE
Option to hide elements

### ISSUE THREAD

**Issue by treyturner** [wswebcreation/webdriver-image-comparison#4]
Hey there, thanks for your work on this. I'm excited at the prospect of getting visual regression back into wdio v5.

Sometimes I want to capture an element while hiding other elements that may exist within or on top of it. The location and size of the elements I want to hide can change, so I'd like to approach it more programmatically.

The previous wdio-visual-regression service had a "hide" option when checking that I presume would set CSS `display: none` on the specified elements prior to capturing. It seems that might be useful here.

If there's a way to achieve this that I missed or if this request is better suited to wdio-image-comparison-service, I can move it over there. Thanks for your consideration!

**Comment by wswebcreation** [comment]
Hi @treyturner 

Thanks for this. You are also in the right place regarding your question. I flagged it as a feature and would be a good first PR 😉

**Comment by wswebcreation** [comment]
Hi @treyturner 

I've implemented this now in the latest version of this module. I can hopefully release a new version of `wdio-image-comparison-service` in the comming days. Check https://github.com/wswebcreation/webdriver-image-comparison/pull/11 for the output on what it can do now

**Comment by wswebcreation** [comment]
@treyturner

I've just released a `1.0.0` release of `wdio-image-comparison-service`. CAn you please verify it and check if it is working for you, if so, can you please close this issue?

**Comment by MortenGregersen** [comment]
It works with hideAfterFirstScroll 🎉
