### ISSUE TITLE
Undefined object exception when evaluating versionOffsets.ADDRESS_BAR with iOS13 Safari

### ISSUE THREAD

**Issue by robotiq-ncarrier** [wswebcreation/webdriver-image-comparison#42]
**Environment (please complete the following information):**
 - Node.js version: v12.3.1
 - NPM version: 6.9.0
 - Browser name and version: Safari 13.1
 - Platform name and version: iPhone 11 XCodeSimulator
 - Framework name and version: wdio
 - Plugin name and version: wdio-image-comparison-service 1.6.0
 - webdriver-image-comparison version: 0.9.1

**Config of the automation framework + plugin**
A part of my wdio.conf file:

```
    capabilities:[{
      maxInstances: 1,
      browserName: 'Safari',
      platformName: 'ios',
      'safari:useSimulator': true,
      'safari:deviceType': 'iPhone',
    }],

  services: ['selenium-standalone',
              ['image-comparison', {
                baselineFolder: join(process.cwd(), visualComparisonDirectory, 'baseline'),
                formatImageName: '{tag}-{deviceName}-{width}x{height}',
                screenshotPath: join(process.cwd(), visualComparisonDirectory, 'screenshots'),
                savePerInstance: true,
                autoSaveBaseline: true,
                blockOutStatusBar: true,
                blockOutToolBar: true,
              }],
```

**Describe the bug**

When executing a test with a browser.checkScreen command (or any other command which takes screenshots), an exception occurs:

`A JavaScript exception occured: undefined is not an object (evaluating 'versionOffsets.ADDRESS_BAR')`

**To Reproduce**

- Setup XCode and start a iPhone simulator with iOS 13.1
- Start a test which contains a browser.checkScreen() command.

**Expected behavior**

The test shoud take screenshot and compare them like with the previous versions of iOS.

**Additional context**

After some investigation I realized that there are no OFFSETS defined for iOS13 in file lib/helpers/constants.ts. It seems to work when I manually add values but I can't find the correct real values for this device.

**Comment by wswebcreation** [comment]
@robotiq-ncarrier 

Thanks for filing this issue, it was my bad that I didn't update the module. I've create a PR https://github.com/wswebcreation/webdriver-image-comparison/pull/43 but have some issues with iPhone 11 Pro and Max which I need to solve

**Comment by wswebcreation** [comment]
Hi @robotiq-ncarrier 

I've released version https://github.com/wswebcreation/wdio-image-comparison-service/releases/tag/v1.7.0

There is still an issue with the toolbar blockout, but only on the iPhone 11 Pro and Max, see also https://github.com/wswebcreation/webdriver-image-comparison/issues/44

Can you please test if it is working for you?

**Comment by nickcarrier** [comment]
Hi @wswebcreation ,

Thank you for your quick support.

I've checked with your latest version and the exception doesn't occur anymore, of course. But I'm still having issue with offset in my screenshots similar to what you have in #44.

I'm testing on XCode Simulator with iOS 13.1 without Appium. When I do a `browser.checkElement()` command, my screenshots are offsetted whichever device I use. When I change the ADDRESS_BAR and STATUS_BAR offsets to '0', it's fine.

Is it a different issue or there's something wrong the way I use browser.checkElement()?

**Comment by wswebcreation** [comment]
Hi @nickcarrier,

Can you please files new issue with all info and the screenshots?

Tnx
