### ISSUE TITLE
Is it possible to remove warning message on console?

### ISSUE THREAD

**Issue by WarleyGabriel** [wswebcreation/webdriver-image-comparison#46]
Hi, 

I would like to know if it is possible to not have the console log:
```
#####################################################################################
 WARNING:
 There was a difference. Saved the difference to
 /home/chk_user/code/test-report/screenshots/diff/desktop_chrome/dois-campos-adicionais-nao-informados-cadastro-de-usuario--1919x1079.png
#####################################################################################
```

 - Node.js version: v10.15.3
 - NPM version: 6.4.1
 - Browser name and version: Chrome 77.0.3865.75
 - Platform name and version: Linux
 - Framework name and version: WebdriverIO 5.13.2
 - Plugin name and version: wdio-image-comparison-service 1.6.0
 - webdriver-image-comparison version: 1.6.0

I created a method to validate the image, and try it again with WebdriverIO waitUntil.
So, I don't need the console log on my screen.

```
visualRegressionElement(element, arquivo) {
        element.waitForDisplayed();
        element.scrollIntoView();
        browser.waitForDisplayedInViewport(element);
        browser.waitUntil(
            () => {
                const diff = browser.checkElement(element, arquivo);
                return diff < 0.15;
            },
            null,
            `Elemento com seletor: '${element.selector}' não está conforme imagem de referência: ${arquivo}`,
        );
    },
```

**Comment by wswebcreation** [comment]
Hi @WarleyGabriel 

Thanks for submitting an issue. Just to give you some insights:

- The log is created by [webdriver-image-comparison](https://github.com/wswebcreation/webdriver-image-comparison/)
- For now this can't be disabled (want to create a PR for it 😉 )
- The log is there to notify users what is happening and what the module is doing.

I'd like to ask you to submit the issue [here](https://github.com/wswebcreation/webdriver-image-comparison/issues) and close it here. Maybe even create a PR

Grtz

**Comment by WarleyGabriel** [comment]
Hi @wswebcreation

Thanks for answered.

What do you think about save the log in file, with the wdio logs?
Maybe we can use the `outputDir` from wdio.

Or, print the logs only when `debug` param is true?

**Comment by wswebcreation** [comment]
Thanks for the PR, I've release https://github.com/wswebcreation/webdriver-image-comparison/releases/tag/v0.11.0 and will release a new version of `wdio-image-comparison-service` in a few minutes

**Comment by WarleyGabriel** [comment]
@wswebcreation Thank you! 👍
