### ISSUE TITLE
formatImageName docs copy pasta

### ISSUE THREAD

**Issue by treyturner** [wswebcreation/webdriver-image-comparison#5]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/wswebcreation/webdriver-image-comparison) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [x] Other

**Description of the improvement / report**
The `formatImageName` [docs](https://github.com/wswebcreation/webdriver-image-comparison/blob/master/docs/OPTIONS.md#formatimagename) appears to be copy pasta as most of the properties are all described as orientation. Also, the defaults for me appear to be empty strings instead of those listed.

**Comment by wswebcreation** [comment]
Thanks for the issue, I just fixed the docs
