### ISSUE TITLE
Feature Request: Screenshot fail gracefully when removeElements non-existing

### ISSUE THREAD

**Issue by Christopher-Hayes** [wswebcreation/webdriver-image-comparison#57]
**Is your feature request related to a problem? Please describe.**
I have elements that only exist on certain pages and the library not finding one of the remove elements causes the screenshot to never be taken. For me, it isn't critical that every element in `removeElements` is removed. I just want the elements that do exist to be removed and non-existing ones to be ignored because some can be intermittent (ex: random sales popup).

**Describe the solution you'd like**
I would like the screenshot function (like `saveFullPageScreen()`) to first check if an element exists before attempting to remove it, or at least fail in a way that doesn't stop the screenshot from being taken.

**Describe alternatives you've considered**
My current solution is to create a `removeElements` array ahead of the `saveFullPageScreen()` by first checking `isDisplayed()` on each element before passing that to the `saveFullPageScreen()` options.

**Additional context**
It looks like xPath doesn't like elements that don't exist, causes the function to fail. For context in the error below `.lp_promo_banner` is the element by trying to hide that doesn't exist on all pages. 
![image](https://user-images.githubusercontent.com/6013871/76425119-90d38880-637f-11ea-93cd-ecc65d487eab.png)
If it's useful, my (simplified) function call looks like:

    browser.saveFullPageScreen(path, {
        removeElements: [
            $('.lp_promo_banner')
        ]
    })

**Comment by wswebcreation** [comment]
@Christopher-Hayes 

Going to fix this with a console warning like this

![image](https://user-images.githubusercontent.com/11979740/79631285-882d5980-8158-11ea-9464-01f4316c885c.png)

Will be released soon

**Comment by wswebcreation** [comment]
@Christopher-Hayes 

I've released version https://github.com/wswebcreation/wdio-image-comparison-service/releases/tag/v1.13.0. Can you please check it and if fixed close the issue?
