### ISSUE TITLE
Browser platform and version variables for formatImageName

### ISSUE THREAD

**Issue by treyturner** [wswebcreation/webdriver-image-comparison#6]
Hi again; I'd like to save the browser platform and major version as part of the screenshot filename. Variables for these values which could be used in formatImageName would be perfect, but I'm open to other solutions as well. Thanks for your time!

**Comment by wswebcreation** [comment]
Hi @treyturner 

Thanks for your issue. This is a nice feature to add. Can you give some examples on how you would like to to be shown?

**Comment by treyturner** [comment]
For browser platform, I'd be looking for whatever is in the driver capabilities, be that `WIN10`, `Windows`, `MAC`, etc.

For major browser version, I'd be looking for `v73` for Chrome or `v66` for Firefox (as examples(, but if I could only get the full version (`v66.0.2` for Firefox) that would work too.

**Comment by wswebcreation** [comment]
@treyturner 

I've release a new version of this module , `0.7.0` and a new version of `dio-image-comparison-service` (https://github.com/wswebcreation/wdio-image-comparison-service/releases/tag/v1.4.0), can you please verify it and if it is as you expect close the issue?

**Comment by wswebcreation** [comment]
@iamkenos

See the above 😉

**Comment by iamkenos** [comment]
I'm getting `not-known` on `{browserVersion}`, running on Chrome 75.
idk why but `browser.capabilities.version` doesnt work on Chrome 75. `browser.capabilities.browserVersion` works though.

**Comment by wswebcreation** [comment]
@iamkenos ,

🤔 , when I run it on my local machine it works, which version of WebdriverIO are you using (version in and you package and package-lock)

**Comment by iamkenos** [comment]
package.json:
```
    "@wdio/allure-reporter": "^5.11.0",
    "@wdio/browserstack-service": "^5.11.0",
    "@wdio/cli": "^5.11.0",
    "@wdio/cucumber-framework": "^5.11.0",
    "@wdio/junit-reporter": "^5.11.0",
    "@wdio/local-runner": "^5.11.0",
    "@wdio/selenium-standalone-service": "^5.11.0",
    "@wdio/spec-reporter": "^5.11.0",
    "@wdio/sync": "^5.11.0",
    "webdriverio": "^5.11.0",
    "wdio-image-comparison-service": "^1.4.0",
```

package-lock:
```
    "webdriverio": {
      "version": "5.11.7",
     ....

    "@wdio/cucumber-framework": {
      "version": "5.11.9",
     ....

    "wdio-image-comparison-service": {
      "version": "1.4.0",
     ....
```

selenium (standalone):
```
  seleniumInstallArgs: {
    version: "3.14.0",
    baseURL: "https://selenium-release.storage.googleapis.com",
    drivers: {
      chrome: {
        version: "75.0.3770.140",
        baseURL: "https://chromedriver.storage.googleapis.com"
      }
    }
  }
```

**Comment by wswebcreation** [comment]
Hmm, can you create a sample project so I can debug it?

**Comment by wswebcreation** [comment]
Going to close this one due to inactivity
