### ISSUE TITLE
disableCSSAnimation breaks transform-Transformations

### ISSUE THREAD

**Issue by michael42** [wswebcreation/webdriver-image-comparison#69]
**Config of the automation framework + plugin**
`{disableCSSAnimation: true}`

**Describe the bug**
Hi there, thanks for the project. We enabled `disableCSSAnimation`, so that we don't have to disable animations ourselves. Unfortunately, this caused our page to render incorrectly, so we had to disable it again.

**To Reproduce**
1. Assume a page that uses `transform`, for example to [center elements](https://codepen.io/chriscoyier/embed/BvdgL?type=result&safe=true).
1. Set `disableCSSAnimation: true`.
1. The `transform: none !important;` now causes the page to render incorrectly.

**Expected behavior**
[setCustomCss](https://github.com/wswebcreation/webdriver-image-comparison/blob/c3802e2e9ec7b443bbd4c28ef05130150a33feb5/lib/clientSideScripts/setCustomCss.ts) should simply not set `transform: none !important;` (and the vendor-prefixed variants).

**Comment by wswebcreation** [comment]
Hi @michael42 

Thanks for this issue, `transform` is also part of the animations, any idea how to do this better? Also care for a PR?

**Comment by michael42** [comment]
Simply removing the lines should work fine, as `transform` is just a static transform. Only `animation` or `transition` are actually doing the animation.

**Comment by wswebcreation** [comment]
@michael42 

Thanks for the PR, I've released a new version https://github.com/wswebcreation/wdio-image-comparison-service/releases/tag/v1.13.3
