### ISSUE TITLE
hideScrollbars doesn't work in mobile emulation

### ISSUE THREAD

**Issue by vmrgvn** [wswebcreation/webdriver-image-comparison#92]
Hi!

I'm trying to make and compare screenshots on the mobile version of my site, but I have noticed that scrollbars don't hide despite hideScrollbars parameter is set to true. 

There is project example with result screenshot:
https://github.com/vmrgvn/image-comparison

Please, help me to find out the problem. 
Thanks!

**Environment (please complete the following information):**
 - Node.js version: v15.12.0
 - NPM version: 7.6.3
 - Browser name and version: Chrome 9 
 - Platform name and version: macOS (Catalina)

**To Reproduce**
Use the project configuration above

**Comment by imolater** [comment]
Hi. I've also faced this problem. Capabilities: Moon, chrome last stable version with mobile emulation and dev.
<img width="605" alt="Снимок экрана 2021-07-13 в 10 16 28" src="https://user-images.githubusercontent.com/26197551/125409005-280d7d80-e3c4-11eb-9b31-e18e1d5fc839.png">

**Comment by yunj** [comment]
Same here. Thanks.
