### ISSUE TITLE
Tool bar and status bar not ignored on mobile android devices

### ISSUE THREAD

**Issue by MPSwift** [wswebcreation/webdriver-image-comparison#96]
**Environment:**
 - Node.js version: v14.15.0
 - NPM version: 7.19.0
 - Browser name and version: Chrome
 - Platform name and version: Android 9
 - Framework name and version: webdriverio v7
 - webdriver-image-comparison version: 3.0.0

**Config of the automation framework + plugin**
Using Lambdatest https://www.lambdatest.com/ to use mobile devices and device capability is 
{
                build: "Test Run",
                name : "Test Galaxy S10 Android 9",
                browserName : "Chrome",
                platform : "Android",
                deviceName : "Galaxy S10",
                platformVersion : "9"
            }

**Describe the bug**
Method saveFullPageScreen does not remove/ignore toolbar and statusbar in chrome android 9 devices, see screenshot
![galaxy_s9-preact-360x740](https://user-images.githubusercontent.com/53569023/132697657-69062ebd-f956-436e-9ca5-014aee39836b.png)

**To Reproduce**
```
 browser.url('https://preactjs.com/');
        browser.saveFullPageScreen(imageName, {
            fullPageScrollTimeout: 3000,
        });
```

**Expected behavior**
toolbar and status bar on chrome android 9 devices is ignored/not visible in full page screenshot

Hi, I'm trying to take and compare full page screenshots on android devices. I'm not using saucelabs or browserstack, I'm using lambdatest (mentioned above).
On iOS devices it's all fine, but on android devices the toolbar and statusbar are not irgnored. ` blockOutStatusBar: true,
            blockOutToolBar: true` are set.

Can you please help?

**Comment by wswebcreation** [comment]
@MPSwift 

Hmm, kinda strange, I'm getting this when I run it on a Samsung S10 in the Sauce Labs cloud. Can you share the instance from Lambda test so I can do some debugging?

![samsung-s10--412x869](https://user-images.githubusercontent.com/11979740/132703839-ba0969db-9ee1-4bba-b20c-c411163d7e33.png)

**Comment by MPSwift** [comment]
Sorry, I cannot share the instance but maybe you can start a free trail here https://www.lambdatest.com/pricing?utm_source=GoogleAds&utm_medium=Sitelink&utm_campaign=Brand&utm_term=FreeTrial&gclid=Cj0KCQjw4eaJBhDMARIsANhrQACN3NYWhP6zgQ1THc9tlPjgaVUEStfckBOvx9x_vw0FUOPRRQxNddwaAhIaEALw_wcB 

Is that ok for you?

**Comment by ThilovGlan** [comment]
Is there any news on this or what information is still required?
