### ISSUE TITLE
ansi-regex vulnerability report

### ISSUE THREAD

**Issue by staizen-alexm** [wswebcreation/webdriver-image-comparison#98]
**Describe your question with as much detail as possible**
A clear and concise question that doesn't require too much conversation. Need more help? [Find me on Gitter](https://gitter.im/wswebcreation)

Not sure if this is something we can handle on this package but we're getting this vulnerability alert:
![image](https://user-images.githubusercontent.com/81152923/140464671-b0f5f4e8-e011-49d2-9cd2-504818e6b314.png)

Any chance we can handle it on  `webdriver-image-comparison` and `wdio-image-comparison-service`?

**Environment (please complete the following information):**
 - Node.js version: `v14.16.1`
 - NPM version: `6.14.12`
 - webdriver-image-comparison version: `0.19.0`

**Additional context**

**Comment by wswebcreation** [comment]
Thanks for reporting this, it should have been fixed now with the latest version
